#!/usr/bin/with-contenv bash

# wait for Wayland to be running
export XDG_RUNTIME_DIR=/tmp
export WAYLAND_DISPLAY=wayland-0
while true; do
  if [ -e "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" ]; then
    break
  fi
  sleep .5
done

# set cursor theme for Wayland
mkdir -p "${HOME}/.config"
echo "XCURSOR_THEME=breeze" > "${HOME}/.config/wayland-cursor"

chown -R abc:abc "${HOME}/.config"
chmod 777 /tmp/selkies*

# run
cd $HOME
exec s6-setuidgid abc \
  /bin/bash /defaults/startwm.sh &
PID=$!
echo "$PID" > /de-pid
wait "$PID"
