#!/usr/bin/with-contenv bash

# default file copies first run - labwc config
if [[ ! -f /config/.config/labwc/autostart ]]; then
  mkdir -p /config/.config/labwc
  if [ -f /defaults/autostart ]; then
    cp /defaults/autostart /config/.config/labwc/autostart
  fi
  chown -R abc:abc /config/.config/labwc
fi
if [[ ! -f /config/.config/labwc/rc.xml ]]; then
  mkdir -p /config/.config/labwc && \
  cp /etc/xdg/labwc/rc.xml /config/.config/labwc/rc.xml && \
  chown -R abc:abc /config/.config
fi

# XDG Home - use /tmp for Wayland
printf "/tmp" > /run/s6/container_environment/XDG_RUNTIME_DIR
if [ ! -d "/tmp" ]; then
  mkdir -p /tmp
  chmod 1777 /tmp
fi

# Locale Support
if [ ! -z ${LC_ALL+x} ]; then
  printf "${LC_ALL%.UTF-8}" > /run/s6/container_environment/LANGUAGE
  printf "${LC_ALL}" > /run/s6/container_environment/LANG
fi

# labwc decoration settings
if [[ ! -z ${NO_DECOR+x} ]] && [[ ! -f /decorlock ]]; then
  # Server-side decorations are already configured in rc.xml
  touch /decorlock
fi

# labwc fullscreen - not needed as apps can control their own state
if [[ ! -z ${NO_FULL+x} ]] && [[ ! -f /fulllock ]]; then
  touch /fulllock
fi

# Add proot-apps
if [ ! -f "${HOME}/.local/bin/proot-apps" ]; then
  mkdir -p ${HOME}/.local/bin/
  cp /proot-apps/* ${HOME}/.local/bin/
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
  chown abc:abc \
    ${HOME}/.bashrc \
    ${HOME}/.local/ \
    ${HOME}/.local/bin \
    ${HOME}/.local/bin/{ncat,proot-apps,proot,jq,pversion}
elif ! diff -q /proot-apps/pversion ${HOME}/.local/bin/pversion > /dev/null; then
  cp /proot-apps/* ${HOME}/.local/bin/
  chown abc:abc ${HOME}/.local/bin/{ncat,proot-apps,proot,jq,pversion}
fi



# set env based on vars
if [[ -z ${NO_GAMEPAD+x} ]]; then
  printf "/usr/lib/selkies_joystick_interposer.so:/opt/lib/libudev.so.1.0.0-fake" > /run/s6/container_environment/LD_PRELOAD
fi

# JS folder setup
mkdir -pm1777 /dev/input
touch /tmp/selkies_js.log
mknod /dev/input/js0 c 13 0
mknod /dev/input/js1 c 13 1
mknod /dev/input/js2 c 13 2
mknod /dev/input/js3 c 13 3
mknod /dev/input/event1000 c 13 1064
mknod /dev/input/event1001 c 13 1065
mknod /dev/input/event1002 c 13 1066
mknod /dev/input/event1003 c 13 1067
chmod 777 /dev/input/js* /dev/input/event* /tmp/selkies*

# Manifest creation
echo "{
  \"name\": \"${TITLE}\",
  \"short_name\": \"${TITLE}\",
  \"manifest_version\": 2,
  \"version\": \"1.0.0\",
  \"display\": \"fullscreen\",
  \"background_color\": \"#000000\",
  \"theme_color\": \"#000000\",
  \"icons\": [
    {
      \"src\": \"icon.png\",
      \"type\": \"image/png\",
      \"sizes\": \"180x180\"
    }
  ],
  \"start_url\": \"/\"
}" > /usr/share/selkies/www/manifest.json
